import type { BranchMindLanguage } from "@/lib/language";

const zhCopy = {
  common: {
    active: "已启用",
    back: "返回",
    cancel: "取消",
    close: "关闭",
    copy: "复制",
    copied: "已复制",
    create: "创建",
    creating: "创建中...",
    curricula: "课程",
    delete: "删除",
    edit: "编辑",
    english: "English",
    exportPdf: "导出 PDF",
    help: "帮助",
    home: "首页",
    import: "导入",
    importJson: "导入 JSON",
    importing: "导入中...",
    menu: "菜单",
    notes: "笔记",
    projects: "项目",
    retry: "重试",
    save: "保存",
    saved: "已保存",
    saving: "保存中...",
    search: "搜索",
    settings: "设置",
    signIn: "登录",
    signOut: "退出登录",
    signingOut: "退出中...",
    usage: "用量",
    zh: "中文",
  },
  accountMenu: {
    accountMenu: "账号菜单",
    accountUnavailable: "账号不可用",
    almostAtLimit: "接近上限",
    branchMindAccount: "BranchMind 账号",
    helpSupport: "帮助与支持",
    localDevMode: "本地开发模式",
    loadingUserAccount: "正在加载账号",
    reportBug: "报告问题",
    signedIn: "已登录",
    unavailableLabel: "账号状态不可用",
    upgrade: "升级",
    userProfile: "用户资料",
    userSignIn: "用户登录",
    whatsNew: "最新功能",
    whatsNewItems: [
      {
        version: "v0.2.0",
        date: "2026 年 5 月",
        title: "账号与账单",
        description: "新增用户套餐、用量统计和设置。免费方案含 5 个项目、100 个节点和 3 份 PDF。",
      },
      {
        version: "v0.1.5",
        date: "2026 年 5 月",
        title: "PDF 阅读器 + RAG",
        description: "上传 PDF、建立索引，并提出带页码引用的问题。可将 PDF 附加到 BranchMind 对话中。",
      },
      {
        version: "v0.1.0",
        date: "2026 年 4 月",
        title: "BranchMind 发布",
        description: "可视化分支式 AI 对话工作区。向下延续或向右开分支来探索想法。",
      },
    ],
  },
  auth: {
    accountName: "账号名",
    accountNameTaken: "该账号名已被使用，请换一个。",
    alreadyHaveAccount: "已经有账号？",
    authFailed: "认证失败。",
    authRequired: "请先登录后再执行此操作。",
    backHome: "首页",
    branchMindAccount: "BranchMind 账号",
    chooseNewPassword: "设置新密码",
    confirmPassword: "确认密码",
    continueWithGoogle: "使用 Google 继续",
    createAccount: "创建账号",
    createOne: "创建一个",
    creatingAccount: "创建中...",
    forgotEyebrow: "恢复暂不可用",
    googleMissingUrl: "Google 登录没有返回跳转地址。",
    googleSignInFailed: "Google 登录失败。",
    hidePassword: "隐藏密码",
    needAccount: "还没有账号？",
    password: "密码",
    recoveryStatus: "如果该账号支持恢复，重置链接会发送给你。",
    rememberedIt: "想起来了？",
    resetPassword: "重置密码",
    secureAccount: "保护你的账号",
    sendResetLink: "发送重置链接",
    sending: "发送中...",
    showPassword: "显示密码",
    signIn: "登录",
    signInFailed: "账号名或密码不正确。",
    signingIn: "登录中...",
    signUpEyebrow: "账号名注册",
    signUpFailed: "无法创建账号，请稍后重试。",
    updatePassword: "更新密码",
    updating: "更新中...",
    validationAccountRequired: "请输入账号名。",
    validationAccountShort: "账号名至少需要 3 个字符。",
    validationAccountLong: "账号名不能超过 32 个字符。",
    validationAccountChars: "账号名只能包含字母、数字、点、下划线和连字符。",
    validationPasswordShort: "密码至少需要 8 个字符。",
    validationPasswordLong: "密码不能超过 128 个字符。",
    validationPasswordMismatch: "两次输入的密码不一致。",
  },
  billing: {
    activeSubscription: "订阅已生效",
    checkoutComing: "结账集成将在第二阶段上线。",
    comingSoon: "即将推出",
    communitySupport: "社区支持",
    current: "当前",
    currentPlan: "当前方案",
    currentPlanCta: "当前方案",
    currentPlanTitle: (plan: string) => `${plan} 套餐`,
    dedicatedSupport: "专属支持",
    freeDescription: "适合清晰试用 BranchMind 的入门方案。",
    freeFeatures: [
      { label: "5 个项目" },
      { label: "100 个节点" },
      { label: "3 份 PDF 文档" },
      { label: "每日 50 条 AI 消息" },
      { label: "社区支持" },
    ],
    freeTier: "免费方案",
    freePlanBody: "免费版适合试用 BranchMind。Pro 会在工作区增长时移除项目和节点上限。",
    invoices: "发票",
    invoicesDescription: "你的账单记录会显示在这里。",
    maxDescription: "解锁所有工作区限制。",
    maxEyebrow: "最大空间",
    maxFeatures: [
      { label: "全部不限量" },
      { label: "共享工作区" },
      { label: "无限知识库" },
      { label: "无限 AI 消息" },
      { label: "专属支持" },
    ],
    noBillingRequired: "无需账单",
    noInvoices: "暂无发票。",
    perMonth: "/月",
    planActive: "方案已启用",
    prioritySupport: "优先支持",
    proBody: "Pro 解锁无限项目和节点，并提供 10 倍每日 AI 消息额度。",
    proDescription: "移除限制，继续构建。",
    proEyebrow: "最佳升级",
    proFeatures: [
      { label: "无限项目", highlight: true },
      { label: "无限节点", highlight: true },
      { label: "50 份 PDF 文档" },
      { label: "每日 500 条 AI 消息" },
      { label: "优先支持" },
    ],
    recommended: "推荐",
    starterLimits: "入门限制",
    stripeComing: "Stripe 集成将在第二阶段上线，敬请期待！",
    unlimitedEverything: "全部不限量",
    unlimitedKnowledgeBase: "无限知识库",
    unlimitedMessages: "无限 AI 消息",
    unlimitedNodes: "无限节点",
    unlimitedProjects: "无限项目",
    upgradedBody: "你的工作区已升级，拥有更多文档、想法和 AI 工作空间。",
    upgradePath: "升级路径",
    upgradeToPro: "升级到 Pro",
  },
  bugReport: {
    attachScreenshot: "添加截图",
    closeForm: "关闭问题报告表单",
    contactEmail: "联系邮箱",
    description: "描述",
    descriptionPlaceholder: "发生了什么？你预期会怎样？",
    helper: "详情会直接发送到管理员队列。",
    reportBug: "报告问题",
    reportSent: "已发送。",
    screenshotTooLarge: "截图必须不超过 5 MB。",
    screenshotType: "截图必须是 PNG、JPG 或 WebP。",
    submitReport: "提交报告",
    submitting: "提交中...",
    submitFailed: "提交失败。",
    title: "标题",
    titlePlaceholder: "一句话概括问题",
  },
  chat: {
    addAttachment: "添加附件",
    addFilesKnowledge: "添加文件或知识库",
    autoModel: "自动",
    chatModels: "聊天模型",
    chooseChatModel: "选择聊天模型",
    chooseFiles: "选择文件",
    couldNotLoadPdfs: "无法加载 PDF。",
    failed: "失败",
    indexed: "已索引",
    ingesting: "处理中",
    knowledgeBase: "知识库",
    knowledgePdf: "知识库 PDF",
    knowledgePdfs: "知识库 PDF",
    loadingPdfs: "正在加载 PDF",
    noIndexedPdfs: "还没有已索引的 PDF。",
    notConfigured: " · 未配置",
    modelApiNotConfigured: "API 尚未配置",
    modelCatalogLoadFailed: "模型加载失败",
    modelCatalogLoading: "正在加载模型…",
    modelLocked: "需要升级",
    retryModelCatalog: "重试",
    pendingAttachments: "待发送附件",
    pdfIndexingFailed: "PDF 索引失败。",
    pdfIndexingRunning: "PDF 仍在索引，请稍后再发送。",
    pdfUploadFailed: "PDF 上传失败。",
    pdfUploadMissingId: "PDF 上传没有返回文档 ID。",
    preparing: "准备中...",
    selected: "已选择",
    skill: "技能",
    skillActive: "已启用技能",
    skillEmpty: "还没有导入技能。",
    skillImport: "导入技能…",
    skillImportError: "无法导入该技能文件夹。",
    skillInvalidFile: "所选文件夹需要包含根 SKILL.md 文件。",
    skillDefault: "内置",
    skillRemove: "移除技能",
    unknownType: "未知类型",
    uploading: "上传中",
    uploadNewFile: "上传新文件",
  },
  home: {
    composerPlaceholder: "输入一个研究问题，BranchMind 会把理解路径拆成可探索的分支...",
    draftNodeSummary: "输入一个研究问题，创建你的分支学习画布。",
    newNode: "新节点",
    newWorkspace: "新工作区",
    start: "开始",
    suggestions: [
      ["拆解论文论点", "规划学习路线", "拆分复杂概念"],
      ["找到关键假设", "生成追问清单", "搭建理解地图"],
      ["比较不同观点", "提炼核心问题", "定位知识盲区"],
      ["发散研究方向", "收束行动计划", "整理学习笔记"],
    ],
    taglines: [
      "你可以外包思考，但是无法外包理解。",
      "把复杂问题拆开，理解会自己长出来。",
      "每一次追问，都是一条新的思路分支。",
      "让灵感发散，让理解收束。",
    ],
  },
  help: {
    ctaSignIn: "登录账号",
    ctaTitle: "准备好把下一个复杂主题学成地图了吗？",
    ctaWorkspace: "进入工作区",
    contactBugNote: "发现问题？也可以通过账号菜单中的“报告问题”入口直接提交。",
    contactEmailLabel: "support@branchmind.app",
    contactTitle: "联系支持",
    eyebrow: "可视化知识工作区",
    faq: [
      {
        question: "BranchMind 和普通 AI 聊天有什么区别？",
        answer:
          "普通聊天是一条直线，BranchMind 是一张地图。你可以向下延续主线，也可以随时向右开分支探索子话题——每个节点拥有独立的对话上下文，分支之间互不干扰。",
      },
      {
        question: "BranchMind 适合什么场景？",
        answer:
          "深度学习与研究：拆解论文论点、规划学习路线、比较不同观点、整理学习笔记——任何需要把复杂知识拆开再收束的场景。",
      },
      {
        question: "可以免费使用吗？",
        answer:
          "可以。免费方案包含 5 个项目、100 个节点、3 份 PDF 文档和每日 50 条 AI 消息，无需绑定账单。",
      },
      {
        question: "支持上传 PDF 吗？",
        answer:
          "支持。上传可选中文本的 PDF 并建立索引后，就能提出带页码引用的有据问题，还可以把 PDF 附加到对话中作为知识上下文。",
      },
      {
        question: "需要注册账号才能开始吗？",
        answer:
          "不需要。打开工作区就能在本地创建第一个项目；登录账号后可以跨设备同步，并解锁更高的使用额度。",
      },
    ],
    faqTitle: "常见问题",
    features: [
      {
        title: "向右分支",
        body: "遇到疑点随时向右开一个分支节点，深入子话题而不打断主线思路。",
      },
      {
        title: "向下继续",
        body: "沿着主线层层递进，把复杂主题按自己的节奏学透。",
      },
      {
        title: "节点级独立上下文",
        body: "每个节点只携带自己的对话上下文，分支之间互不干扰，追问更聚焦。",
      },
      {
        title: "PDF 阅读 + 页码引用",
        body: "上传可选中文本的 PDF，建立索引后提出带页码引用的有据问题。",
      },
    ],
    featuresTitle: "为深度学习而设计",
    footerPrivacy: "隐私政策",
    footerTerms: "使用条款",
    heroLead:
      "BranchMind 是一张会生长的知识地图：沿着主线向下深挖，随时向右开分支探索子话题，每个节点都有独立的对话上下文，还能上传 PDF 提出带页码引用的问题。",
    heroTitle: "把复杂知识学成一张知识地图",
    steps: [
      {
        title: "提出研究问题",
        body: "从一个复杂主题开始，BranchMind 会把理解路径拆成可以探索的分支。",
      },
      {
        title: "分支探索",
        body: "对任何回答继续追问，或向右开分支，把每个疑点展开成独立的子话题。",
      },
      {
        title: "沉淀知识地图",
        body: "节点在画布上连成分支地图，随时可以回顾、导出，或继续生长。",
      },
    ],
    stepsTitle: "三步开始",
  },
  language: {
    description: "选择 BranchMind 的界面语言。登录后会同步到你的账号。",
    englishDescription: "Use English across the core BranchMind interface.",
    englishLabel: "English",
    error: "语言已切换，但同步到账号失败。",
    saved: "语言偏好已保存。",
    saving: "正在保存语言偏好...",
    title: "界面语言",
    zhDescription: "在核心 BranchMind 界面中使用中文。",
    zhLabel: "中文",
  },
  projects: {
    allProjects: "全部项目",
    branchMindHome: "BranchMind 首页",
    cancelProjectName: (title: string) => `取消编辑项目名称：${title}`,
    copySuffix: (index?: number) => (index && index > 1 ? `（副本 ${index}）` : "（副本）"),
    createProject: "创建项目",
    createProjectStatus: "正在创建项目。",
    deleteBody: (title: string) => `这会从 BranchMind 永久删除“${title}”。如果需要备份，请先导出 JSON。`,
    deleting: "删除中...",
    deleteProjectPrompt: "删除项目？",
    deleteProject: (title: string) => `删除 ${title}`,
    duplicateProject: (title: string) => `复制 ${title}`,
    editProject: (title: string) => `编辑 ${title}`,
    exportProjectJson: (title: string) => `将 ${title} 导出为 JSON`,
    filter: "项目筛选",
    helpFeedback: "帮助与反馈",
    importBranchMindJson: "导入 BranchMind JSON 项目",
    importedCount: (imported: number, source: number) => `已导入 ${imported} / ${source} 个项目。`,
    newProject: "新建项目",
    noMatchingProjects: "没有匹配的项目",
    noProjects: "还没有项目",
    noProjectsBody: "用“新建项目”创建一个项目，或导入 BranchMind JSON 导出文件。",
    noProjectsImported: "没有导入新项目。所选项目已存在。",
    nodeCount: (count: number) => `${count} 个节点`,
    openMostRecent: "打开最近项目",
    openMostRecentProject: (title: string) => `打开最近项目：${title}`,
    openProject: (title: string) => `打开 ${title}`,
    pdfReader: "PDF 阅读器",
    projectActions: (title: string) => `${title} 的操作`,
    projectCount: (count: number) => `${count} 个项目`,
    projectLauncher: "项目启动器",
    projectNameFor: (title: string) => `${title} 的项目名称`,
    recent: "最近",
    saveProjectName: (title: string) => `保存项目名称：${title}`,
    searchProjects: "搜索项目",
    sharedWithMe: "与我共享",
    showing: (visible: number, total: number) => `显示 ${visible} / ${total} 个项目`,
    star: (title: string) => `收藏 ${title}`,
    starred: "已收藏",
    tableActions: "操作",
    tableName: "名称",
    tableNodes: "节点数",
    tableUpdated: "更新时间",
    templates: "模板",
    topic: "主题",
    topicPlaceholder: "从一个研究问题开始...",
    tryDifferentTitle: "试试不同的项目标题。",
    unstar: (title: string) => `取消收藏 ${title}`,
  },
  reader: {
    askAnything: "询问这份 PDF...",
    backHome: "返回 BranchMind 首页",
    deletePdf: "删除 PDF",
    documents: "文档",
    download: "下载",
    downloadPdf: "下载 PDF",
    enableAskPdf: "启用 Ask PDF",
    indexToAsk: "索引这份 PDF 后即可提出有依据的问题。",
    loadingPdf: "正在加载 PDF",
    loadingReader: "正在加载阅读器",
    localPreview: "本地预览",
    localPreviewUploading: "本地预览 - 上传中",
    nextPage: "下一页",
    noPdfSelected: "未选择 PDF",
    noPdfs: "还没有 PDF。",
    noSections: "还没有检测到章节。",
    pageNumber: "页码",
    preparingPdf: "准备 PDF",
    previousPage: "上一页",
    ready: "就绪",
    renamePdf: "重命名 PDF",
    renderingPage: "正在渲染页面",
    resizeDocuments: "调整文档侧栏",
    resizeTools: "调整 PDF 工具侧栏",
    savePdfName: "保存 PDF 名称",
    selectPdf: "选择 PDF",
    selectPdfAsk: "选择一份 PDF 后即可提问。",
    selectPdfReading: "选择一份 PDF 开始阅读",
    serviceNotReady: "文档服务尚未完成初始化，请稍后重试或联系管理员。",
    serviceUnavailable: "文档服务暂时不可用，请稍后重试。",
    title: "PDF 阅读器",
    toc: "目录",
    uploadPdf: "上传 PDF",
    uploading: "上传中",
    zoomIn: "放大",
    zoomOut: "缩小",
  },
  settings: {
    accountCenter: "账号中心",
    accountDescription: "管理你的公开资料。",
    accountName: "账号名",
    accountNameDescription: "你的账号名用于密码登录。",
    accountNameLocalDescription: "此环境使用本地存储，因此没有账号名可显示。",
    accountNameMissing: "登录后添加账号名",
    accountNameMissingLocal: "未绑定账号名",
    accountNameMissingSignedOut: "登录后添加账号名",
    accountNameWithValue: "用于账号名和密码登录。",
    appearanceDescription: "选择适合你工作氛围的界面皮肤。",
    appearanceTitle: "界面主题",
    billing: "账单",
    billingShort: "账单",
    cloudAccount: "云端账号",
    deleteAccount: "删除账号",
    deleteAccountConfirmLabel: (accountName: string) => `输入账号名 “${accountName}” 以确认删除`,
    deleteAccountConfirmPlaceholder: "输入账号名",
    deleteAccountDeleting: "删除中...",
    deleteAccountDescription: "永久删除你的账号和全部云端数据。",
    deleteAccountFailed: "删除账号失败，请稍后重试。",
    deleteAccountFinal: "永久删除",
    deleteAccountSignInDescription: "只有云端账号支持删除；本地工作区数据保存在此浏览器中。",
    deleteAccountSignInTitle: "登录后可删除账号",
    deleteAccountWarning: "这会永久删除你的账号、所有项目、PDF 文档和用量数据，且无法撤销。",
    description: "管理你的账号、用量、账单和偏好设置。",
    displayName: "显示名称",
    displayNameDescription: "这个名称会显示在 BranchMind 中。",
    displayNameSaved: "显示名称已更新。",
    displayNamesNeedSignIn: "显示名称会保存在登录账号中。",
    failedUpdate: "更新失败。",
    language: "语言",
    languageShort: "语言",
    localWorkspace: "本地工作区",
    navAccount: "账号",
    navAppearance: "外观",
    navAppearanceShort: "主题",
    navUsage: "用量与限制",
    navUsageShort: "用量",
    noAccountNameLocal: "匿名浏览器会话",
    password: "密码",
    passwordDescription: "更新密码，保持账号安全。",
    passwordLocalDescription: "本地工作区使用匿名浏览器会话，不使用账号密码登录。",
    passwordLocal: "此工作区不使用密码",
    passwordMin: "密码至少需要 8 个字符。",
    passwordMismatch: "两次输入的密码不一致。",
    passwordPlaceholder: "新密码",
    passwordSignInRequired: "登录后更新密码",
    passwordSignInRequiredDescription: "账号会话生效后即可管理密码。",
    passwordUpdated: "密码已更新。",
    profile: "个人资料",
    profileDescription: "你的公开资料信息。",
    save: "保存",
    signedOut: "未登录",
    signInAddAccountName: "登录后选择账号名",
    signInEditName: "登录后编辑名称",
    signInProfile: "请登录后更新资料。",
    signInPassword: "请登录后更新密码。",
    themes: {
      mineral: {
        name: "矿物绿",
        description: "安静的绿色与墨色界面，适合日常工作。",
      },
      "classic-purple": {
        name: "经典紫",
        description: "BranchMind 最初的柔和紫色外观。",
      },
      "warm-limestone": {
        name: "暖石灰岩",
        description: "面向账号中心的温和皮肤，石色中性、瓷感面板和古橄榄点缀。",
      },
    },
    title: "设置",
    usageHistory: "每日用量历史",
    usageHistoryDescription: "最近 30 天的资源使用情况。",
    usageNoHistory: "还没有可用的用量历史。",
    yourDisplayName: "你的显示名称",
  },
  usage: {
    aiMessages: "AI 消息（今日）",
    aiMsgs: "AI 消息",
    date: "日期",
    documents: "PDF 文档",
    limitReached: "已达到上限",
    nodes: "节点",
    pdfs: "PDF",
    projects: "项目",
    used: (percentage: number) => `已用 ${percentage}%`,
  },
  curriculumGeneration: {
    title: "教材生成",
    subtitle: "根据学习目标自动生成结构化教材草案。",
    subjectLabel: "学科 / 主题",
    subjectPlaceholder: "例如：机器学习入门",
    currentLevelLabel: "当前水平",
    beginner: "初学者",
    intermediate: "中级",
    advanced: "高级",
    learningGoalLabel: "学习目标",
    learningGoalPlaceholder: "例如：能用 Python 实现并解释线性回归",
    durationWeeksLabel: "持续周数（可选）",
    hoursPerWeekLabel: "每周小时数（可选）",
    includeMathDepthLabel: "数学深度",
    mathLight: "轻量",
    mathStandard: "标准",
    mathDeep: "深入",
    includeProjectsLabel: "包含项目实践",
    includeProjectsDescription: "在课程末尾加入可交付的实践项目。",
    quotaLoading: "正在查询本月生成额度...",
    quotaUnavailable: "额度信息暂时不可用，仍可尝试生成。",
    quotaRemaining: (remaining: number) => `本月剩余生成次数：${remaining}`,
    quotaUnlimited: "本月生成额度：不限",
    quotaLocal: "本地开发模式不计入云端生成额度。",
    quotaExhausted: "本月额度已用完，额度将在下月 1 日恢复。",
    estimatedDuration: "预计耗时：约 2–4 分钟（以内联生成上限为参考）。",
    generateButton: "生成教材",
    generating: "生成中...",
    reconnecting: "正在恢复进度...",
    polling: "正在同步最新进度...",
    cancelButton: "取消生成",
    resumeButton: "重新生成",
    retryButton: "重试",
    stageLabel: "当前阶段",
    searchesLabel: "搜索查询",
    sourcesLabel: "已选来源",
    validationLabel: "验证结果",
    draftSavedLabel: "已保存为版本",
    viewVersionLink: "查看版本",
    completedTitle: "生成完成",
    failedTitle: "生成失败",
    cancelledTitle: "已取消",
    noResultCount: "等待结果",
    errors: {
      generic: "生成失败，请重试。",
      loadCurriculum: "无法加载课程信息。",
    },
    stages: {
      intake: "需求整理",
      planning: "制定计划",
      searching: "检索资料",
      fetching_sources: "获取来源",
      extracting_concepts: "提取概念",
      building_graph: "构建知识图",
      validating: "验证草案",
      repairing: "修复问题",
      saving_draft: "保存草案",
      completed: "已完成",
      failed: "失败",
      cancelled: "已取消",
    },
  },
  curriculumVersion: {
    title: "教材版本",
    empty: "还没有教材版本。先生成一份教材草案。",
    select: "选择版本",
    preview: "教材预览",
    editLabel: "版本名称",
    save: "保存修改",
    saving: "保存中...",
    derive: "派生新版本",
    deriving: "派生中...",
    publish: "发布教材",
    publishing: "发布中...",
    publishConfirm: "发布后该版本不可修改，确定发布吗？",
    publishDialogTitle: "确认发布教材",
    publishDialogVersion: (versionNumber: number, versionLabel: string) =>
      `版本 v${versionNumber} · ${versionLabel}`,
    publishDialogBlockingWarnings: (count: number) => `阻断警告：${count} 条`,
    publishDialogImmutable: "发布后版本将不可修改；如需调整，请先派生新版本。",
    publishDialogCancel: "暂不发布",
    publishDialogConfirm: "确认发布",
    published: "已发布",
    superseded: "已被替代",
    draft: "草稿",
    modules: "模块",
    nodes: "知识点",
    prerequisites: "前置知识",
    sources: "来源",
    warnings: "校验提示",
    blocking: "阻断",
    advisory: "提示",
    compare: "版本差异",
    compareAgainst: "对比版本",
    noChanges: "没有结构变化",
    changes: (count: number) => `${count} 项变化`,
    diffModules: "模块",
    diffNodes: "知识点",
    diffEdges: "关系",
    diffSources: "来源",
    diffAdded: "新增",
    diffRemoved: "删除",
    diffChanged: "修改",
    assumptions: "生成假设",
    exclusions: "排除范围",
    conflicts: "来源冲突",
    estimatedDuration: "预计学习时长",
    weeks: "周",
    hours: "小时",
    noItems: "暂无",
    changedFields: "变更字段",
    errors: { load: "无法加载教材版本。", save: "保存教材修改失败。" },
  },
  curriculumList: {
    title: "课程",
    description: "创建课程草案，生成教材版本，并在发布前预览内容。",
    createTitle: "创建课程",
    createDescription: "先建立课程容器，再进入详情页生成教材。",
    titleLabel: "课程名称",
    titlePlaceholder: "例如：机器学习基础",
    subjectLabel: "学科 / 主题（可选）",
    subjectPlaceholder: "例如：机器学习",
    goalLabel: "学习目标",
    goalPlaceholder: "例如：能解释并应用常见机器学习方法",
    createButton: "创建并继续",
    creating: "创建中...",
    listTitle: "我的课程",
    empty: "还没有课程，先创建一个吧。",
    loadError: "无法加载课程列表。",
    createError: "创建课程失败。",
  },
  workspace: {
    addLatestAiReply: "添加最新 AI 回复",
    aiMessageLimitReached: (limit: number) => `今天的 AI 消息额度（${limit} 条）已用完，明天再来吧。`,
    askBranchMind: "询问 BranchMind",
    askBranchMindSelection: "询问 BranchMind 关于选中文本",
    backToChat: "返回聊天",
    branch: "分支",
    branchRight: "向右分支",
    newBranchRight: "新建右侧分支",
    cancelMessageEdit: "取消编辑消息",
    chat: "聊天",
    childCount: (count: number) => `${count} 个子节点`,
    closeProjectNotes: "关闭项目笔记",
    closeSidePanels: "关闭侧栏",
    collapseChildrenFor: (title: string) => `收起 ${title} 的子节点`,
    collapseNodeDetails: "收起节点详情面板",
    collapseSidebar: "收起工作区侧栏",
    continue: "继续",
    continueDown: "向下继续",
    conversationHistory: "对话历史",
    conversationOutline: "对话大纲",
    copyRoleMessage: (role: string) => `复制${role === "user" ? "用户" : "助手"}消息`,
    createWorkspace: "创建你的工作区。",
    deleteNode: "删除节点",
    deleteNodeBody: (title: string, descendantCount: number) =>
      descendantCount > 0
        ? `这会永久删除节点“${title}”及其全部 ${descendantCount} 个子节点。`
        : `这会永久删除节点“${title}”。`,
    deleteNodePrompt: "删除节点？",
    editNodeTitle: "编辑节点标题",
    editUserMessage: "编辑用户消息",
    expandChildrenFor: (title: string) => `展开 ${title} 的子节点`,
    expandNode: "展开节点",
    expandNodeDetails: "展开节点详情面板",
    expandSidebar: "展开工作区侧栏",
    fold: "折叠",
    foldNode: "折叠节点",
    thinkingElapsed: (seconds: number) => `正在思考 ${seconds} 秒`,
    initialInstruction: "继续讲下一个关键知识点。",
    loading: "正在加载 BranchMind...",
    map: "地图",
    messageActions: (role: string) => `${role === "user" ? "用户" : "助手"}消息操作`,
    messageComposer: "消息输入框",
    messageInstruction: "消息指令",
    mathFormulaEdit: "编辑数学公式",
    mathFormulaInsert: "插入数学公式",
    mathFormulaSubmitInsert: "插入",
    mathFormulaSubmitUpdate: "更新",
    mathFormulaTitle: "数学公式",
    nodeBrief: "节点摘要",
    nodeDetails: "节点详情",
    nodeNotSelected: "选择一个节点",
    noMatchingNodes: "没有匹配的节点",
    noVisibleNodes: "没有可见节点",
    notesCouldNotSave: "笔记无法保存。",
    notesTooLong: "项目笔记太长。",
    openNode: (title: string) => `打开节点 ${title}`,
    openProjectNotes: "打开项目笔记",
    outline: "大纲",
    preparingPdfAttachments: "正在准备这个节点的 PDF 附件。",
    projectNotFound: "未找到项目",
    projectNotFoundBody: "创建一个新的 BranchMind 项目。",
    projectNotes: "项目笔记",
    projectNotesBlocks: "区块",
    projectNotesPlaceholder: "项目笔记...",
    ready: "就绪",
    removeSelectedText: "移除选中文本上下文",
    resizeConversationComposer: "调整对话历史下方输入框高度",
    resizeConversationHeader: "调整对话历史上方标题区高度",
    resizeNodeDetails: "调整节点详情面板",
    resizeProjectNotes: "调整项目笔记面板",
    resizeSidebar: "调整工作区侧栏",
    sidebar: "工作区侧栏",
    retryAssistant: "重试助手回复",
    regenerateConflict: "这段对话已在其他窗口中被修改，请刷新后重试。",
    root: "根节点",
    saveFailed: "保存失败",
    unsavedChanges: "未保存更改",
    untitledNode: "未命名节点",
    saveMessageEdit: "保存消息编辑",
    saveNodeTitle: "保存节点标题",
    searchNodes: "搜索节点",
    searchProjectNodes: "搜索项目节点",
    selectedTextCount: "1 个已选文本片段",
    send: "发送",
    streamingAnswer: "正在为这个节点生成答案。",
    syncFailed: (error?: string) => `同步失败。${error ?? "你的项目已保存在此浏览器中。"}`,
    toggleChildren: (title: string) => `切换 ${title} 的子节点`,
    toggleChildrenTitle: "切换子节点",
    user: "用户",
    userShort: "用户",
    assistant: "助手",
    askNextQuestion: "继续追问...",
    views: "工作区移动视图",
  },
};

export type LanguageCopy = typeof zhCopy;

export const LANGUAGE_COPY = {
  zh: zhCopy,
  en: {
    common: {
      active: "Active",
      back: "Back",
      cancel: "Cancel",
      close: "Close",
      copy: "Copy",
      copied: "Copied",
      create: "Create",
      creating: "Creating…",
      curricula: "Curricula",
      delete: "Delete",
      edit: "Edit",
      english: "English",
      exportPdf: "Export PDF",
      help: "Help",
      home: "Home",
      import: "Import",
      importJson: "Import JSON",
      importing: "Importing…",
      menu: "Menu",
      notes: "Notes",
      projects: "Projects",
      retry: "Retry",
      save: "Save",
      saved: "Saved",
      saving: "Saving…",
      search: "Search",
      settings: "Settings",
      signIn: "Sign in",
      signOut: "Sign out",
      signingOut: "Signing out…",
      usage: "Usage",
      zh: "中文",
    },
    accountMenu: {
      accountMenu: "Account menu",
      accountUnavailable: "Account unavailable",
      almostAtLimit: "Almost at limit",
      branchMindAccount: "BranchMind account",
      helpSupport: "Help & Support",
      localDevMode: "Local dev mode",
      loadingUserAccount: "Loading user account",
      reportBug: "Report a bug",
      signedIn: "Signed in",
      unavailableLabel: "Account status unavailable",
      upgrade: "Upgrade",
      userProfile: "User profile",
      userSignIn: "User sign-in",
      whatsNew: "What's New",
      whatsNewItems: [
        {
          version: "v0.2.0",
          date: "May 2026",
          title: "Account & Billing",
          description: "Introducing user plans, usage tracking, and Settings. Free plan includes 5 projects, 100 nodes, and 3 PDFs.",
        },
        {
          version: "v0.1.5",
          date: "May 2026",
          title: "PDF Reader + RAG",
          description: "Upload PDFs, index them, and ask questions with page citations. Attach PDFs to BranchMind conversations.",
        },
        {
          version: "v0.1.0",
          date: "April 2026",
          title: "BranchMind Launch",
          description: "Visual branching AI conversation workspace. Continue down or branch right to explore ideas.",
        },
      ],
    },
    auth: {
      accountName: "Account name",
      accountNameTaken: "That account name is already taken.",
      alreadyHaveAccount: "Already have an account?",
      authFailed: "Authentication failed.",
      authRequired: "You need to sign in to do that.",
      backHome: "Home",
      branchMindAccount: "BranchMind account",
      chooseNewPassword: "Choose new password",
      confirmPassword: "Confirm password",
      continueWithGoogle: "Continue with Google",
      createAccount: "Create account",
      createOne: "Create one",
      creatingAccount: "Creating account…",
      forgotEyebrow: "Recovery disabled",
      googleMissingUrl: "Google sign-in couldn't start. Please try again.",
      googleSignInFailed: "Google sign-in failed.",
      hidePassword: "Hide password",
      needAccount: "Need an account?",
      password: "Password",
      recoveryStatus: "If that account supports recovery, a reset link is on the way.",
      rememberedIt: "Remember your password?",
      resetPassword: "Reset password",
      secureAccount: "Secure your account",
      sendResetLink: "Send reset link",
      sending: "Sending…",
      showPassword: "Show password",
      signIn: "Sign in",
      signInFailed: "Invalid account name or password.",
      signingIn: "Signing in…",
      signUpEyebrow: "Create your account",
      signUpFailed: "Unable to create account. Please try again.",
      updatePassword: "Update password",
      updating: "Updating…",
      validationAccountRequired: "Account name is required.",
      validationAccountShort: "Account name must be at least 3 characters.",
      validationAccountLong: "Account name must be 32 characters or fewer.",
      validationAccountChars: "Account name can only include letters, numbers, periods, underscores, and hyphens.",
      validationPasswordShort: "Password must be at least 8 characters.",
      validationPasswordLong: "Password must be 128 characters or fewer.",
      validationPasswordMismatch: "Passwords do not match.",
    },
    billing: {
      activeSubscription: "Active subscription",
      checkoutComing: "Checkout is coming soon.",
      comingSoon: "Coming soon",
      communitySupport: "Community support",
      current: "Current",
      currentPlan: "Current plan",
      currentPlanCta: "Current plan",
      currentPlanTitle: (plan: string) => `${plan} plan`,
      dedicatedSupport: "Dedicated support",
      freeDescription: "A simple starter tier with clear limits.",
      freeFeatures: [
        { label: "5 projects" },
        { label: "100 nodes" },
        { label: "3 PDF documents" },
        { label: "50 AI messages/day" },
        { label: "Community support" },
      ],
      freeTier: "Free tier",
      freePlanBody: "Free is great for trying BranchMind. When your workspace grows, Pro removes the project and node limits.",
      invoices: "Invoices",
      invoicesDescription: "Your billing history will appear here.",
      maxDescription: "Everything, unlimited.",
      maxEyebrow: "Everything unlimited",
      maxFeatures: [
        { label: "Unlimited everything" },
        { label: "Shared workspaces" },
        { label: "Unlimited knowledge-base storage" },
        { label: "Unlimited AI messages" },
        { label: "Dedicated support" },
      ],
      noBillingRequired: "No billing required",
      noInvoices: "No invoices yet.",
      perMonth: "/month",
      planActive: "Plan active",
      prioritySupport: "Priority support",
      proBody: "Pro unlocks unlimited projects and nodes, plus 10x the daily AI messages.",
      proDescription: "Remove limits and keep building.",
      proEyebrow: "Most popular",
      proFeatures: [
        { label: "Unlimited projects", highlight: true },
        { label: "Unlimited nodes", highlight: true },
        { label: "50 PDF documents" },
        { label: "500 AI messages/day" },
        { label: "Priority support" },
      ],
      recommended: "Recommended",
      starterLimits: "Starter",
      stripeComing: "Stripe payments are on the way.",
      unlimitedEverything: "Unlimited everything",
      unlimitedKnowledgeBase: "Unlimited knowledge-base storage",
      unlimitedMessages: "Unlimited AI messages",
      unlimitedNodes: "Unlimited nodes",
      unlimitedProjects: "Unlimited projects",
      upgradedBody: "Your plan is already upgraded — plenty of room for documents, ideas, and AI work.",
      upgradePath: "Upgrade path",
      upgradeToPro: "Upgrade to Pro",
    },
    bugReport: {
      attachScreenshot: "Attach screenshot",
      closeForm: "Close bug report form",
      contactEmail: "Contact email",
      description: "Description",
      descriptionPlaceholder: "What happened? What did you expect?",
      helper: "Sends your report straight to the BranchMind team.",
      reportBug: "Report a bug",
      reportSent: "Report sent.",
      screenshotTooLarge: "Screenshot must be 5 MB or smaller.",
      screenshotType: "Screenshot must be PNG, JPG, or WebP.",
      submitReport: "Submit report",
      submitting: "Submitting…",
      submitFailed: "Failed to submit report.",
      title: "Title",
      titlePlaceholder: "One-line summary",
    },
    chat: {
      addAttachment: "Add attachment",
      addFilesKnowledge: "Add files or knowledge base PDFs",
      autoModel: "Automatic",
      chatModels: "Chat models",
      chooseChatModel: "Choose chat model",
      chooseFiles: "Choose files",
      couldNotLoadPdfs: "Could not load PDFs.",
      failed: "Failed",
      indexed: "Indexed",
      ingesting: "Indexing",
      knowledgeBase: "Knowledge base",
      knowledgePdf: "Knowledge base PDF",
      knowledgePdfs: "Knowledge base PDFs",
      loadingPdfs: "Loading PDFs",
      noIndexedPdfs: "No indexed PDFs yet.",
      notConfigured: " · Not configured",
      modelApiNotConfigured: "API not configured",
      modelCatalogLoadFailed: "Could not load models",
      modelCatalogLoading: "Loading models…",
      modelLocked: "Upgrade required",
      retryModelCatalog: "Retry",
      pendingAttachments: "Pending attachments",
      pdfIndexingFailed: "PDF indexing failed.",
      pdfIndexingRunning: "PDF indexing is still running. Please try again in a moment.",
      pdfUploadFailed: "PDF upload failed.",
      pdfUploadMissingId: "PDF upload did not return a document ID.",
      preparing: "Preparing…",
      selected: "Selected",
      skill: "Skill",
      skillActive: "Active skill",
      skillEmpty: "No imported skills yet.",
      skillImport: "Import skill…",
      skillImportError: "Could not import that skill folder.",
      skillInvalidFile: "The selected folder must contain a root SKILL.md file.",
      skillDefault: "Built-in",
      skillRemove: "Remove skill",
      unknownType: "Unknown type",
      uploading: "Uploading",
      uploadNewFile: "Upload new file",
    },
    home: {
      composerPlaceholder: "Start with a research question and BranchMind will split the path into explorable branches…",
      draftNodeSummary: "Enter a research question to create your branching canvas.",
      newNode: "New node",
      newWorkspace: "New project",
      start: "Start",
      suggestions: [
        ["break down a paper", "plan a study path", "split a complex concept"],
        ["find key assumptions", "generate follow-up questions", "build an understanding map"],
        ["compare viewpoints", "extract the core question", "find knowledge gaps"],
        ["expand research directions", "narrow an action plan", "organize study notes"],
      ],
      taglines: [
        "You can outsource thinking, but not understanding.",
        "Break down complex problems and watch understanding grow.",
        "Every follow-up question opens a new branch.",
        "Let ideas branch out, then let understanding converge.",
      ],
    },
    help: {
      ctaSignIn: "Sign in",
      ctaTitle: "Ready to turn your next complex topic into a map?",
      ctaWorkspace: "Open the workspace",
      contactBugNote: "Found a bug? You can also submit it from the account menu's report-a-bug entry.",
      contactEmailLabel: "support@branchmind.app",
      contactTitle: "Contact support",
      eyebrow: "Visual knowledge workspace",
      faq: [
        {
          question: "How is BranchMind different from a regular AI chat?",
          answer:
            "Regular chat is a straight line; BranchMind is a map. Continue down the main thread or branch right into subtopics — every node keeps its own isolated conversation context.",
        },
        {
          question: "What is BranchMind best for?",
          answer:
            "Deep study and research: breaking down papers, planning study paths, comparing viewpoints, and organizing study notes — anywhere complex knowledge needs to be unpacked and reconnected.",
        },
        {
          question: "Is BranchMind free?",
          answer:
            "Yes. The free plan includes 5 projects, 100 nodes, 3 PDF documents, and 50 AI messages per day — no billing required.",
        },
        {
          question: "Can I upload PDFs?",
          answer:
            "Yes. Upload a selectable-text PDF, index it, ask grounded questions with page citations, and attach it to conversations as knowledge context.",
        },
        {
          question: "Do I need an account to start?",
          answer:
            "No. Open the workspace to create your first project locally; sign in to sync across devices and unlock higher limits.",
        },
      ],
      faqTitle: "Frequently asked questions",
      features: [
        {
          title: "Branch Right",
          body: "Open a branch node for any open question and deep-dive subtopics without losing the main thread.",
        },
        {
          title: "Continue Down",
          body: "Extend the main line and work through a complex topic layer by layer, at your own pace.",
        },
        {
          title: "Isolated node context",
          body: "Each node carries only its own conversation context, so branches never bleed into each other.",
        },
        {
          title: "PDF reader + RAG citations",
          body: "Upload selectable-text PDFs, index them, and ask grounded questions with page citations.",
        },
      ],
      featuresTitle: "Designed for deep study",
      footerPrivacy: "Privacy Policy",
      footerTerms: "Terms of Use",
      heroLead:
        "BranchMind is a living knowledge map: continue down the main thread, branch right into subtopics with isolated per-node context, and ask cited questions over your PDFs.",
      heroTitle: "Turn complex topics into a knowledge map",
      steps: [
        {
          title: "Ask a research question",
          body: "Start with a complex topic and BranchMind splits the path of understanding into explorable branches.",
        },
        {
          title: "Branch to explore",
          body: "Follow up on any answer or branch right to unfold each open question into its own subtopic.",
        },
        {
          title: "Grow the knowledge map",
          body: "Nodes connect into a branching map you can revisit, export, and keep growing.",
        },
      ],
      stepsTitle: "How it works",
    },
    language: {
      description: "Choose the BranchMind interface language. Signed-in accounts sync this preference.",
      englishDescription: "Use English across the core BranchMind interface.",
      englishLabel: "English",
      error: "Language changed, but account sync failed.",
      saved: "Language preference saved.",
      saving: "Saving language preference…",
      title: "Interface Language",
      zhDescription: "在核心 BranchMind 界面中使用中文。",
      zhLabel: "中文",
    },
    projects: {
      allProjects: "All projects",
      branchMindHome: "BranchMind home",
      cancelProjectName: (title: string) => `Cancel project name edit for ${title}`,
      copySuffix: (index?: number) => (index && index > 1 ? ` (Copy ${index})` : " (Copy)"),
      createProject: "Create project",
      createProjectStatus: "Creating project…",
      deleteBody: (title: string) => `This permanently removes "${title}" from BranchMind. Export JSON first if you need a copy.`,
      deleting: "Deleting…",
      deleteProjectPrompt: "Delete project?",
      deleteProject: (title: string) => `Delete ${title}`,
      duplicateProject: (title: string) => `Duplicate ${title}`,
      editProject: (title: string) => `Edit ${title}`,
      exportProjectJson: (title: string) => `Export ${title} as JSON`,
      filter: "Project filter",
      helpFeedback: "Help & feedback",
      importBranchMindJson: "Import BranchMind JSON project",
      importedCount: (imported: number, source: number) => `Imported ${imported} of ${source} ${source === 1 ? "project" : "projects"}.`,
      newProject: "New Project",
      noMatchingProjects: "No matching projects",
      noProjects: "No projects yet.",
      noProjectsBody: "Select New Project to create one, or import a BranchMind JSON export.",
      noProjectsImported: "No new projects were imported — they already exist in your library.",
      nodeCount: (count: number) => `${count} ${count === 1 ? "node" : "nodes"}`,
      openMostRecent: "Open most recent project",
      openMostRecentProject: (title: string) => `Open most recent project, ${title}`,
      openProject: (title: string) => `Open ${title}`,
      pdfReader: "PDF Reader",
      projectActions: (title: string) => `${title} actions`,
      projectCount: (count: number) => `${count} ${count === 1 ? "project" : "projects"}`,
      projectLauncher: "Project launcher",
      projectNameFor: (title: string) => `Project name for ${title}`,
      recent: "Recent",
      saveProjectName: (title: string) => `Save project name for ${title}`,
      searchProjects: "Search projects",
      sharedWithMe: "Shared with me",
      showing: (visible: number, total: number) => `Showing ${visible} of ${total} projects`,
      star: (title: string) => `Star ${title}`,
      starred: "Starred",
      tableActions: "Actions",
      tableName: "Name",
      tableNodes: "Nodes",
      tableUpdated: "Updated",
      templates: "Templates",
      topic: "Topic",
      topicPlaceholder: "Start with a research question…",
      tryDifferentTitle: "Try a different project title.",
      unstar: (title: string) => `Unstar ${title}`,
    },
    reader: {
      askAnything: "Ask anything about this PDF…",
      backHome: "Back to BranchMind home",
      deletePdf: "Delete PDF",
      documents: "Documents",
      download: "Download",
      downloadPdf: "Download PDF",
      enableAskPdf: "Enable Ask PDF",
      indexToAsk: "Index this PDF to ask questions with page citations.",
      loadingPdf: "Loading PDF",
      loadingReader: "Loading reader",
      localPreview: "Local preview",
      localPreviewUploading: "Local preview — uploading",
      nextPage: "Next page",
      noPdfSelected: "No PDF selected",
      noPdfs: "No PDFs yet.",
      noSections: "No sections detected yet.",
      pageNumber: "Page number",
      preparingPdf: "Preparing PDF",
      previousPage: "Previous page",
      ready: "Ready",
      renamePdf: "Rename PDF",
      renderingPage: "Rendering page",
      resizeDocuments: "Resize documents sidebar",
      resizeTools: "Resize PDF tools sidebar",
      savePdfName: "Save PDF name",
      selectPdf: "Select a PDF",
      selectPdfAsk: "Select a PDF to ask questions.",
      selectPdfReading: "Select a PDF to start reading.",
      serviceNotReady: "The document service isn't fully set up yet. Please try again later or contact an administrator.",
      serviceUnavailable: "The document service is temporarily unavailable. Please try again later.",
      title: "PDF Reader",
      toc: "Contents",
      uploadPdf: "Upload PDF",
      uploading: "Uploading",
      zoomIn: "Zoom in",
      zoomOut: "Zoom out",
    },
    settings: {
      accountCenter: "Account center",
      accountDescription: "Manage your public profile.",
      accountName: "Account name",
      accountNameDescription: "Your account name is used for password sign-in.",
      accountNameLocalDescription: "You're using a local workspace, so there's no account name to show.",
      accountNameMissing: "Sign in to add an account name",
      accountNameMissingLocal: "No account name attached",
      accountNameMissingSignedOut: "Sign in to add an account name",
      accountNameWithValue: "Used to sign in with your account name and password.",
      appearanceDescription: "Choose the theme that best matches your preferred working atmosphere.",
      appearanceTitle: "Interface theme",
      billing: "Billing",
      billingShort: "Billing",
      cloudAccount: "Cloud account",
      deleteAccount: "Delete account",
      deleteAccountConfirmLabel: (accountName: string) => `Type your account name "${accountName}" to confirm deletion`,
      deleteAccountConfirmPlaceholder: "Account name",
      deleteAccountDeleting: "Deleting…",
      deleteAccountDescription: "Permanently delete your account and all cloud data.",
      deleteAccountFailed: "Failed to delete the account. Please try again.",
      deleteAccountFinal: "Delete permanently",
      deleteAccountSignInDescription: "Account deletion is available for cloud accounts; local workspace data stays in this browser.",
      deleteAccountSignInTitle: "Sign in to delete your account",
      deleteAccountWarning: "This permanently deletes your account, every project, PDF document, and usage record. This cannot be undone.",
      description: "Manage your account, usage, billing, and preferences.",
      displayName: "Display name",
      displayNameDescription: "This is how your name appears across BranchMind.",
      displayNameSaved: "Display name updated.",
      displayNamesNeedSignIn: "Sign in to save a display name.",
      failedUpdate: "Failed to update.",
      language: "Language",
      languageShort: "Language",
      localWorkspace: "Local workspace",
      navAccount: "Account",
      navAppearance: "Appearance",
      navAppearanceShort: "Theme",
      navUsage: "Usage & limits",
      navUsageShort: "Usage",
      noAccountNameLocal: "Anonymous browser session",
      password: "Password",
      passwordDescription: "Update your password to keep your account secure.",
      passwordLocalDescription: "Local workspaces use an anonymous browser session instead of an account name and password.",
      passwordLocal: "Password is not used in this workspace.",
      passwordMin: "Password must be at least 8 characters.",
      passwordMismatch: "Passwords do not match.",
      passwordPlaceholder: "New password",
      passwordSignInRequired: "Sign in to update your password",
      passwordSignInRequiredDescription: "You can change your password once you're signed in.",
      passwordUpdated: "Password updated successfully.",
      profile: "Profile",
      profileDescription: "Your public profile information.",
      save: "Save",
      signedOut: "Signed out",
      signInAddAccountName: "Sign in to choose an account name",
      signInEditName: "Sign in to edit your name",
      signInProfile: "Sign in to update your profile.",
      signInPassword: "Sign in to update your password.",
      themes: {
        mineral: {
          name: "Mineral",
          description: "A quiet green and ink interface for everyday work.",
        },
        "classic-purple": {
          name: "Classic Purple",
          description: "The original soft purple BranchMind look.",
        },
        "warm-limestone": {
          name: "Warm Limestone",
          description: "Warm stone neutrals with porcelain panels and antique olive accents.",
        },
      },
      title: "Settings",
      usageHistory: "Daily usage history",
      usageHistoryDescription: "Last 30 days of resource usage.",
      usageNoHistory: "No usage history available yet.",
      yourDisplayName: "Your display name",
    },
    usage: {
      aiMessages: "AI messages (today)",
      aiMsgs: "AI messages",
      date: "Date",
      documents: "PDF Documents",
      limitReached: "Limit reached",
      nodes: "Nodes",
      pdfs: "PDFs",
      projects: "Projects",
      used: (percentage: number) => `${percentage}% used`,
    },
    curriculumGeneration: {
      title: "Curriculum Generation",
      subtitle: "Generate a structured curriculum draft from your learning goal.",
      subjectLabel: "Subject / Topic",
      subjectPlaceholder: "e.g. Introduction to Machine Learning",
      currentLevelLabel: "Current Level",
      beginner: "Beginner",
      intermediate: "Intermediate",
      advanced: "Advanced",
      learningGoalLabel: "Learning Goal",
      learningGoalPlaceholder: "e.g. Implement and explain linear regression in Python",
      durationWeeksLabel: "Duration in weeks (optional)",
      hoursPerWeekLabel: "Hours per week (optional)",
      includeMathDepthLabel: "Math depth",
      mathLight: "Light",
      mathStandard: "Standard",
      mathDeep: "Deep",
      includeProjectsLabel: "Include project practice",
      includeProjectsDescription: "Add deliverable projects to the end of the curriculum.",
      quotaLoading: "Checking this month's generation quota...",
      quotaUnavailable: "Quota information is temporarily unavailable; you can still try generating.",
      quotaRemaining: (remaining: number) => `Generations remaining this month: ${remaining}`,
      quotaUnlimited: "Monthly generation quota: unlimited",
      quotaLocal: "Local development mode is not counted against cloud quota.",
      quotaExhausted: "This month's quota is exhausted. It resets on the first day of next month.",
      estimatedDuration: "Estimated time: about 2–4 minutes (based on the inline generation limit).",
      generateButton: "Generate Curriculum",
      generating: "Generating...",
      reconnecting: "Restoring progress...",
      polling: "Syncing latest progress...",
      cancelButton: "Cancel Generation",
      resumeButton: "Regenerate",
      retryButton: "Retry",
      stageLabel: "Current Stage",
      searchesLabel: "Search Queries",
      sourcesLabel: "Selected Sources",
      validationLabel: "Validation Result",
      draftSavedLabel: "Saved as version",
      viewVersionLink: "View version",
      completedTitle: "Generation Complete",
      failedTitle: "Generation Failed",
      cancelledTitle: "Cancelled",
      noResultCount: "Waiting for results",
      errors: {
        generic: "Generation failed. Please try again.",
        loadCurriculum: "Unable to load curriculum information.",
      },
      stages: {
        intake: "Intake",
        planning: "Planning",
        searching: "Searching",
        fetching_sources: "Fetching Sources",
        extracting_concepts: "Extracting Concepts",
        building_graph: "Building Graph",
        validating: "Validating",
        repairing: "Repairing",
        saving_draft: "Saving Draft",
        completed: "Completed",
        failed: "Failed",
        cancelled: "Cancelled",
      },
    },
    curriculumVersion: {
      title: "Curriculum Versions",
      empty: "No curriculum versions yet. Generate a draft first.",
      select: "Select version",
      preview: "Curriculum preview",
      editLabel: "Version label",
      save: "Save changes",
      saving: "Saving...",
      derive: "Derive version",
      deriving: "Deriving...",
      publish: "Publish curriculum",
      publishing: "Publishing...",
      publishConfirm: "This version cannot be edited after publishing. Publish it?",
      publishDialogTitle: "Confirm curriculum publication",
      publishDialogVersion: (versionNumber: number, versionLabel: string) =>
        `Version v${versionNumber} · ${versionLabel}`,
      publishDialogBlockingWarnings: (count: number) => `Blocking warnings: ${count}`,
      publishDialogImmutable: "Published versions cannot be edited. Derive a new version to make changes.",
      publishDialogCancel: "Not now",
      publishDialogConfirm: "Confirm publication",
      published: "Published",
      superseded: "Superseded",
      draft: "Draft",
      modules: "Modules",
      nodes: "Nodes",
      prerequisites: "Prerequisites",
      sources: "Sources",
      warnings: "Validation warnings",
      blocking: "Blocking",
      advisory: "Advisory",
      compare: "Version diff",
      compareAgainst: "Compare against",
      noChanges: "No structural changes",
      changes: (count: number) => `${count} change${count === 1 ? "" : "s"}`,
      diffModules: "Modules",
      diffNodes: "Nodes",
      diffEdges: "Edges",
      diffSources: "Sources",
      diffAdded: "Added",
      diffRemoved: "Removed",
      diffChanged: "Changed",
      assumptions: "Assumptions",
      exclusions: "Exclusions",
      conflicts: "Source conflicts",
      estimatedDuration: "Estimated study time",
      weeks: "weeks",
      hours: "hours",
      noItems: "None",
      changedFields: "Changed fields",
      errors: { load: "Unable to load curriculum versions.", save: "Unable to save curriculum changes." },
    },
    curriculumList: {
      title: "Curricula",
      description: "Create curriculum drafts, generate versions, and preview them before publishing.",
      createTitle: "Create a curriculum",
      createDescription: "Create the curriculum container first, then generate its draft on the detail page.",
      titleLabel: "Curriculum title",
      titlePlaceholder: "e.g. Machine Learning Foundations",
      subjectLabel: "Subject / topic (optional)",
      subjectPlaceholder: "e.g. Machine learning",
      goalLabel: "Learning goal",
      goalPlaceholder: "e.g. Explain and apply common machine learning methods",
      createButton: "Create and continue",
      creating: "Creating...",
      listTitle: "My curricula",
      empty: "No curricula yet. Create one to get started.",
      loadError: "Unable to load curricula.",
      createError: "Unable to create the curriculum.",
    },
    workspace: {
      addLatestAiReply: "Add latest AI reply",
      aiMessageLimitReached: (limit: number) => `You've used all ${limit} AI messages for today. Come back tomorrow.`,
      askBranchMind: "Ask BranchMind",
      askBranchMindSelection: "Ask BranchMind about selected text",
      backToChat: "Back to chat",
      branch: "Branch",
      branchRight: "Branch right",
      newBranchRight: "New right-side branch",
      cancelMessageEdit: "Cancel message edit",
      chat: "Chat",
      childCount: (count: number) => `${count} ${count === 1 ? "child" : "children"}`,
      closeProjectNotes: "Close project notes",
      closeSidePanels: "Close side panels",
      collapseChildrenFor: (title: string) => `Collapse children for ${title}`,
      collapseNodeDetails: "Collapse node details panel",
      collapseSidebar: "Collapse workspace sidebar",
      continue: "Continue",
      continueDown: "Continue down",
      conversationHistory: "Conversation history",
      conversationOutline: "Conversation outline",
      copyRoleMessage: (role: string) => `Copy ${role} message`,
      createWorkspace: "Creating your project…",
      deleteNode: "Delete node",
      deleteNodeBody: (title: string, descendantCount: number) =>
        descendantCount > 0
          ? `This permanently deletes "${title}" and its ${descendantCount} child ${descendantCount === 1 ? "node" : "nodes"}.`
          : `This permanently deletes "${title}".`,
      deleteNodePrompt: "Delete node?",
      editNodeTitle: "Edit node title",
      editUserMessage: "Edit user message",
      expandChildrenFor: (title: string) => `Expand children for ${title}`,
      expandNode: "Expand node",
      expandNodeDetails: "Expand node details panel",
      expandSidebar: "Expand workspace sidebar",
      fold: "Fold",
      foldNode: "Fold node",
      thinkingElapsed: (seconds: number) => `Thinking for ${seconds}s`,
      initialInstruction: "Continue with the next key concept.",
      loading: "Loading BranchMind…",
      map: "Map",
      messageActions: (role: string) => `${role} message actions`,
      messageComposer: "Message composer",
      messageInstruction: "Message instruction",
      mathFormulaEdit: "Edit math formula",
      mathFormulaInsert: "Insert math formula",
      mathFormulaSubmitInsert: "Insert",
      mathFormulaSubmitUpdate: "Update",
      mathFormulaTitle: "Math formula",
      nodeBrief: "Node brief",
      nodeDetails: "Node details",
      nodeNotSelected: "Select a node",
      noMatchingNodes: "No matching nodes",
      noVisibleNodes: "No visible nodes",
      notesCouldNotSave: "Notes could not be saved.",
      notesTooLong: "Project notes are too long.",
      openNode: (title: string) => `Open node ${title}`,
      openProjectNotes: "Open project notes",
      outline: "Outline",
      preparingPdfAttachments: "Preparing PDF attachments for this node.",
      projectNotFound: "Project not found",
      projectNotFoundBody: "Create a new BranchMind project.",
      projectNotes: "Project notes",
      projectNotesBlocks: "Blocks",
      projectNotesPlaceholder: "Project notes…",
      ready: "Ready",
      removeSelectedText: "Remove selected text context",
      resizeConversationComposer: "Resize composer height below conversation history",
      resizeConversationHeader: "Resize header height above conversation history",
      resizeNodeDetails: "Resize node details panel",
      resizeProjectNotes: "Resize project notes panel",
      resizeSidebar: "Resize workspace sidebar",
      sidebar: "Workspace sidebar",
      retryAssistant: "Retry assistant response",
      regenerateConflict: "This conversation was updated in another window. Refresh and try again.",
      root: "Root",
      saveFailed: "Save failed",
      unsavedChanges: "Unsaved changes",
      untitledNode: "Untitled node",
      saveMessageEdit: "Save message edit",
      saveNodeTitle: "Save node title",
      searchNodes: "Search nodes",
      searchProjectNodes: "Search project nodes",
      selectedTextCount: "1 text snippet selected",
      send: "Send",
      streamingAnswer: "Streaming answer for this node.",
      syncFailed: (error?: string) => `Sync failed. ${error ?? "Your project is saved in this browser."}`,
      toggleChildren: (title: string) => `Toggle children for ${title}`,
      toggleChildrenTitle: "Toggle children",
      user: "user",
      userShort: "You",
      assistant: "assistant",
      askNextQuestion: "Ask a follow-up question…",
      views: "Workspace mobile views",
    },
  },
} satisfies Record<BranchMindLanguage, LanguageCopy>;
