import {
  assertPublicHttpsUrl,
  type SafeFetchedPage,
  type SafeWebFetcher,
} from "@/lib/research/safe-web-fetcher";

// Fixed timestamp keeps generated pages deterministic for test assertions.
const MOCK_FETCHED_AT = "2026-01-01T00:00:00.000Z";

function generatePage(url: string, parsed: URL): SafeFetchedPage {
  return {
    url,
    canonicalUrl: parsed.toString(),
    title: `Mock page for ${parsed.hostname}`,
    content: [
      `Deterministic mock page content for ${url}.`,
      "Generated by MockSafeWebFetcher; no network request was made.",
    ].join("\n"),
    fetchedAt: MOCK_FETCHED_AT,
    truncated: false,
  };
}

// Deterministic fake fetcher for tests, CI, and E2E (spec §15.5). Fixtures are
// keyed by the exact URL string; unknown URLs get a generated page. SSRF
// validation runs even in the mock so tests cover the rejection paths.
export class MockSafeWebFetcher implements SafeWebFetcher {
  readonly id = "mock";

  private readonly fixtures: Record<string, SafeFetchedPage>;

  constructor(fixtures: Record<string, SafeFetchedPage> = {}) {
    this.fixtures = fixtures;
  }

  async fetch(url: string): Promise<SafeFetchedPage> {
    const parsed = assertPublicHttpsUrl(url);
    return this.fixtures[url] ?? generatePage(url, parsed);
  }
}
